# Heart Health Ensemble

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import sqlalchemy
from sqlalchemy import create_engine
from config import db_password

# Read Data and Perform Data Cleaning(?)

In [3]:
# database string
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/heart_disease"

In [4]:
# database setup; which is subject to change
engine = create_engine(db_string)

In [5]:
# use the engine to execute SQL code and store in result variable
result = engine.execute("SELECT HD.*, AR.AgeRiskBin, DBB.DiabetesBin, SR.RecSleepBin \
FROM HeartDisease as HD \
INNER JOIN AgeRisk as AR ON HD.AgeCategory=AR.AgeCategory \
INNER JOIN DiabetesBins as DBB ON HD.Diabetic=DBB.Diabetic \
INNER JOIN SleepRecommendation as SR ON HD.SleepTime=SR.SleepTime;")

In [6]:
# put result into a dataframe
heart_disease_df = pd.DataFrame(result)
heart_disease_df.columns = result._metadata.keys
print(heart_disease_df.shape)
heart_disease_df.head()

(319795, 22)

,heartdisease,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,sex,agecategory,...,physicalactivity,genhealth,sleeptime,asthma,kidneydisease,skincancer,id_g5,ageriskbin,diabetesbin,recsleepbin
0,False,16.60,True,False,False,3,30,False,Female,55-59,...,True,Very good,5,True,False,True,1,Medium Risk,Yes,Below
1,False,20.34,False,False,True,0,0,False,Female,80 or older,...,True,Very good,7,False,False,False,2,High Risk,No,Meets
2,False,26.58,True,False,False,20,30,False,Male,65-69,...,True,Fair,8,True,False,False,3,High Risk,Yes,Meets
3,False,24.21,False,False,False,0,0,False,Female,75-79,...,False,Good,6,False,False,True,4,High Risk,No,Below
4,False,23.71,False,False,False,28,0,True,Female,40-44,...,True,Very good,8,False,False,False,5,Low Risk,No,Meets

In [7]:
heart_disease_df.columns

Index(['heartdisease', 'bmi', 'smoking', 'alcoholdrinking', 'stroke',
       'physicalhealth', 'mentalhealth', 'diffwalking', 'sex', 'agecategory',
       'race', 'diabetic', 'physicalactivity', 'genhealth', 'sleeptime',
       'asthma', 'kidneydisease', 'skincancer', 'id_g5', 'ageriskbin',
       'diabetesbin', 'recsleepbin'],
      dtype='object')

In [8]:
# Drop the null columns where all values are null
heart_disease_df = heart_disease_df.dropna(axis='columns', how='all')

# Drop the null rows
heart_disease_df = heart_disease_df.dropna()

# Looks like we didn't lose any rows
heart_disease_df.shape

(319795, 22)

In [10]:
# ready the data for the ML model by deleting the columns that have been recoded and the series variable id_g5
df = heart_disease_df.drop(["agecategory", "sleeptime", "diabetic", "id_g5" ], axis = 1)

# rename the recoded columns with the old column names so it's uniform with what we have already written
df.rename(columns = {'ageriskbin':'agecategory', 'recsleepbin':'sleeptime',
                              'diabetesbin':'diabetic'}, inplace = True)

# reorder the columns 
df = df[['heartdisease', 'bmi', 'smoking', 'alcoholdrinking', 'stroke',
       'physicalhealth', 'mentalhealth', 'diffwalking', 'sex', 'agecategory',
       'race', 'diabetic', 'physicalactivity', 'genhealth', 'sleeptime',
       'asthma', 'kidneydisease', 'skincancer']]

# check the df
print(df.shape)
df.head()

(319795, 18)

,heartdisease,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,sex,agecategory,race,diabetic,physicalactivity,genhealth,sleeptime,asthma,kidneydisease,skincancer
0,False,16.60,True,False,False,3,30,False,Female,Medium Risk,White,Yes,True,Very good,Below,True,False,True
1,False,20.34,False,False,True,0,0,False,Female,High Risk,White,No,True,Very good,Meets,False,False,False
2,False,26.58,True,False,False,20,30,False,Male,High Risk,White,Yes,True,Fair,Meets,True,False,False
3,False,24.21,False,False,False,0,0,False,Female,High Risk,White,No,False,Good,Below,False,False,True
4,False,23.71,False,False,False,28,0,True,Female,Low Risk,White,No,True,Very good,Meets,False,False,False

In [12]:
# Apply LabelEncoder module to all columns containing string values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
string_columns = [    
    "heartdisease",
    "smoking",
    "alcoholdrinking",
    "stroke",
    "diffwalking",
    "sex",
    "agecategory",
    "race",
    "diabetic",
    "physicalactivity",
    "sleeptime",
    "asthma",
    "kidneydisease",
    "skincancer"    ]
df2 = df.copy()
df2[string_columns] = df2[string_columns].apply(le.fit_transform)
df2.head()

,heartdisease,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,sex,agecategory,race,diabetic,physicalactivity,genhealth,sleeptime,asthma,kidneydisease,skincancer
0,0,16.60,1,0,0,3,30,0,0,2,5,1,1,Very good,1,1,0,1
1,0,20.34,0,0,1,0,0,0,0,0,5,0,1,Very good,2,0,0,0
2,0,26.58,1,0,0,20,30,0,1,0,5,1,1,Fair,2,1,0,0
3,0,24.21,0,0,0,0,0,0,0,0,5,0,0,Good,1,0,0,1
4,0,23.71,0,0,0,28,0,1,0,1,5,0,1,Very good,2,0,0,0

#  Separate the Features (X) from the Target (y)

In [13]:
# Create our features
X = df.drop(columns="heartdisease", axis=1 )
X = pd.get_dummies(X)

# Create our target
y = df["heartdisease"]

In [14]:
pd.set_option('display.max_columns', None)
X.head()

,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,physicalactivity,asthma,kidneydisease,skincancer,sex_Female,sex_Male,agecategory_High Risk,agecategory_Low Risk,agecategory_Medium Risk,race_American Indian/Alaskan Native,race_Asian,race_Black,race_Hispanic,race_Other,race_White,diabetic_No,diabetic_Yes,genhealth_Excellent,genhealth_Fair,genhealth_Good,genhealth_Poor,genhealth_Very good,sleeptime_Above,sleeptime_Below,sleeptime_Meets
0,16.60,True,False,False,3,30,False,True,True,False,True,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0
1,20.34,False,False,True,0,0,False,True,False,False,False,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
2,26.58,True,False,False,20,30,False,True,True,False,False,0,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1
3,24.21,False,False,False,0,0,False,False,False,False,True,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0
4,23.71,False,False,False,28,0,True,True,False,False,False,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1

In [15]:
X.shape

(319795, 32)

# Split Data into Training and Testing

In [16]:
#Split the data inot Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  random_state=78, train_size=0.80)

# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(255836, 32)
(63959, 32)
(255836,)
(63959,)

In [17]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Undersampling

In [18]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({False: 21960, True: 21960})

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [20]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[43728, 14818],
       [ 1318,  4095]], dtype=int64)

In [21]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.7517059870512306

In [22]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

      False       0.97      0.75      0.76      0.84      0.75      0.56     58546
       True       0.22      0.76      0.75      0.34      0.75      0.57      5413

avg / total       0.91      0.75      0.76      0.80      0.75      0.56     63959