In [14]:
# import dependencies
import sqlalchemy
from sqlalchemy import create_engine
from config import db_password
import pandas as pd

In [15]:
# database string
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/heart_disease"

In [16]:
# database setup; which is subject to change
engine = create_engine(db_string)

In [17]:
# use the engine to execute SQL code and store in result variable
result = engine.execute("SELECT HD.*, AR.AgeRiskBin, DBB.DiabetesBin, SR.RecSleepBin \
FROM HeartDisease as HD \
INNER JOIN AgeRisk as AR ON HD.AgeCategory=AR.AgeCategory \
INNER JOIN DiabetesBins as DBB ON HD.Diabetic=DBB.Diabetic \
INNER JOIN SleepRecommendation as SR ON HD.SleepTime=SR.SleepTime;")

In [18]:
# put result into a dataframe
heart_disease_df = pd.DataFrame(result)
heart_disease_df.columns = result._metadata.keys
print(heart_disease_df.shape)
heart_disease_df.head()

(319795, 22)

,heartdisease,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,sex,agecategory,...,physicalactivity,genhealth,sleeptime,asthma,kidneydisease,skincancer,id_g5,ageriskbin,diabetesbin,recsleepbin
0,False,16.60,True,False,False,3,30,False,Female,55-59,...,True,Very good,5,True,False,True,1,Medium Risk,Yes,Below
1,False,20.34,False,False,True,0,0,False,Female,80 or older,...,True,Very good,7,False,False,False,2,High Risk,No,Meets
2,False,26.58,True,False,False,20,30,False,Male,65-69,...,True,Fair,8,True,False,False,3,High Risk,Yes,Meets
3,False,24.21,False,False,False,0,0,False,Female,75-79,...,False,Good,6,False,False,True,4,High Risk,No,Below
4,False,23.71,False,False,False,28,0,True,Female,40-44,...,True,Very good,8,False,False,False,5,Low Risk,No,Meets

In [20]:
heart_disease_df.columns

Index(['heartdisease', 'bmi', 'smoking', 'alcoholdrinking', 'stroke',
       'physicalhealth', 'mentalhealth', 'diffwalking', 'sex', 'agecategory',
       'race', 'diabetic', 'physicalactivity', 'genhealth', 'sleeptime',
       'asthma', 'kidneydisease', 'skincancer', 'id_g5', 'ageriskbin',
       'diabetesbin', 'recsleepbin'],
      dtype='object')

In [19]:
# Drop the null columns where all values are null
heart_disease_df = heart_disease_df.dropna(axis='columns', how='all')

# Drop the null rows
heart_disease_df = heart_disease_df.dropna()

# Looks like we didn't lose any rows
heart_disease_df.shape

(319795, 22)

In [21]:
# ready the data for the ML model by deleting the columns that have been recoded and the series variable id_g5
df = heart_disease_df.drop(["agecategory", "sleeptime", "diabetic", "id_g5" ], axis = 1)

# rename the recoded columns with the old column names so it's uniform with what we have already written
df.rename(columns = {'ageriskbin':'agecategory', 'recsleepbin':'sleeptime',
                              'diabetesbin':'diabetic'}, inplace = True)

# reorder the columns 
df = df[['heartdisease', 'bmi', 'smoking', 'alcoholdrinking', 'stroke',
       'physicalhealth', 'mentalhealth', 'diffwalking', 'sex', 'agecategory',
       'race', 'diabetic', 'physicalactivity', 'genhealth', 'sleeptime',
       'asthma', 'kidneydisease', 'skincancer']]

# check the df
print(df.shape)
df.head()

(319795, 18)

,heartdisease,bmi,smoking,alcoholdrinking,stroke,physicalhealth,mentalhealth,diffwalking,sex,agecategory,race,diabetic,physicalactivity,genhealth,sleeptime,asthma,kidneydisease,skincancer
0,False,16.60,True,False,False,3,30,False,Female,Medium Risk,White,Yes,True,Very good,Below,True,False,True
1,False,20.34,False,False,True,0,0,False,Female,High Risk,White,No,True,Very good,Meets,False,False,False
2,False,26.58,True,False,False,20,30,False,Male,High Risk,White,Yes,True,Fair,Meets,True,False,False
3,False,24.21,False,False,False,0,0,False,Female,High Risk,White,No,False,Good,Below,False,False,True
4,False,23.71,False,False,False,28,0,True,Female,Low Risk,White,No,True,Very good,Meets,False,False,False